In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/crime-data-from-2010-to-2019/Crime_Data_from_2010_to_2019.csv

In [2]:
crime=pd.read_csv('/kaggle/input/crime-data-from-2010-to-2019/Crime_Data_from_2010_to_2019.csv')
crime

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2149680,190506304,02/22/2019 12:00:00 AM,02/22/2019 12:00:00 AM,840,5,Harbor,569,2,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,...,AO,Adult Other,627.0,NaN,NaN,NaN,100 W 22ND ST,NaN,33.7257,-118.2801
2149681,190608903,03/28/2019 12:00:00 AM,03/28/2019 12:00:00 AM,400,6,Hollywood,644,1,648,ARSON,...,IC,Invest Cont,648.0,NaN,NaN,NaN,1400 N LA BREA AV,NaN,34.0962,-118.3490
2149682,192004409,01/06/2019 12:00:00 AM,01/06/2019 12:00:00 AM,2100,20,Olympic,2029,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,IC,Invest Cont,930.0,NaN,NaN,NaN,6TH,VIRGIL,34.0637,-118.2870
2149683,191716777,10/17/2019 12:00:00 AM,10/16/2019 12:00:00 AM,1800,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2149684,190805435,02/01/2019 12:00:00 AM,02/01/2019 12:00:00 AM,1615,8,West LA,852,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [3]:
crime.head(5)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488

In [4]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149685 entries, 0 to 2149684
Data columns (total 28 columns):
 #   Column          Dtype
---  ------          -----
 0   DR_NO           int64
 1   Date Rptd       object
 2   DATE OCC        object
 3   TIME OCC        int64
 4   AREA            int64
 5   AREA NAME       object
 6   Rpt Dist No     int64
 7   Part 1-2        int64
 8   Crm Cd          int64
 9   Crm Cd Desc     object
 10  Mocodes         object
 11  Vict Age        int64
 12  Vict Sex        object
 13  Vict Descent    object
 14  Premis Cd       float64
 15  Premis Desc     object
 16  Weapon Used Cd  float64
 17  Weapon Desc     object
 18  Status          object
 19  Status Desc     object
 20  Crm Cd 1        float64
 21  Crm Cd 2        float64
 22  Crm Cd 3        float64
 23  Crm Cd 4        float64
 24  LOCATION        object
 25  Cross Street    object
 26  LAT             float64
 27  LON             float64
dtypes: float64(8), int64(7), object(13)
memory usage: 459.2+ MB

In [5]:
crime.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,2.149685e+06,2.149685e+06,2.149685e+06,2.149685e+06,2.149685e+06,2.149685e+06,2.149685e+06,2.149639e+06,722680.000000,2.149675e+06,143136.000000,3714.000000,109.000000,2.149685e+06,2.149685e+06
mean,1.503180e+08,1.359212e+03,1.112653e+01,1.159038e+03,1.444874e+00,5.070179e+02,3.170392e+01,3.111911e+02,370.965104,5.068358e+02,949.250279,972.671513,977.431193,3.405980e+01,-1.182950e+02
std,3.124922e+07,6.472014e+02,6.016534e+00,6.016534e+02,4.969520e-01,2.106236e+02,2.068611e+01,2.116291e+02,113.869585,2.104811e+02,125.426174,83.866863,78.749176,8.029225e-01,2.761386e+00
min,1.208575e+06,1.000000e+00,1.000000e+00,1.000000e+02,1.000000e+00,1.100000e+02,-1.200000e+01,1.010000e+02,101.000000,1.100000e+02,210.000000,93.000000,421.000000,0.000000e+00,-1.188279e+02
25%,1.215149e+08,9.300000e+02,6.000000e+00,6.440000e+02,1.000000e+00,3.300000e+02,2.000000e+01,1.020000e+02,400.000000,3.300000e+02,998.000000,998.000000,998.000000,3.401020e+01,-1.184372e+02
50%,1.513051e+08,1.430000e+03,1.200000e+01,1.204000e+03,1.000000e+00,4.420000e+02,3.200000e+01,2.100000e+02,400.000000,4.420000e+02,998.000000,998.000000,998.000000,3.406230e+01,-1.183294e+02
75%,1.721086e+08,1.900000e+03,1.600000e+01,1.682000e+03,2.000000e+00,6.260000e+02,4.600000e+01,5.010000e+02,400.000000,6.260000e+02,998.000000,998.000000,998.000000,3.417580e+01,-1.182777e+02
max,9.102204e+08,2.359000e+03,2.100000e+01,2.199000e+03,2.000000e+00,9.560000e+02,1.180000e+02,9.710000e+02,516.000000,9.990000e+02,999.000000,999.000000,999.000000,3.479070e+01,0.000000e+00

In [6]:
crime.shape

(2149685, 28)

In [7]:
crime.corr()

/tmp/ipykernel_20/2959462628.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  crime.corr()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
DR_NO,1.000000,-0.015635,0.059636,0.059720,-0.018435,-0.005417,0.005458,-0.008836,0.003959,-0.005867,-0.103905,0.026345,0.143807,0.002444,-0.000516
TIME OCC,-0.015635,1.000000,0.011095,0.011288,-0.056184,0.011719,-0.047835,-0.089303,-0.003194,0.011771,0.013172,0.003855,-0.081183,0.000933,-0.000251
AREA,0.059636,0.011095,1.000000,0.999010,0.001407,-0.004637,0.001802,0.006558,-0.008430,-0.004800,-0.056716,-0.019490,0.062950,0.046315,-0.010540
Rpt Dist No,0.059720,0.011288,0.999010,1.000000,0.001234,-0.004701,0.002061,0.006488,-0.008246,-0.004864,-0.056097,-0.018183,0.063716,0.045968,-0.010623
Part 1-2,-0.018435,-0.056184,0.001407,0.001234,1.000000,0.730610,0.139111,0.232997,0.433431,0.730883,0.075398,-0.044188,0.105500,-0.001571,0.003934
Crm Cd,-0.005417,0.011719,-0.004637,-0.004701,0.730610,1.000000,-0.036379,0.104818,0.419119,0.999502,0.038707,0.109604,0.097887,-0.004234,0.005549
Vict Age,0.005458,-0.047835,0.001802,0.002061,0.139111,-0.036379,1.000000,0.167660,0.080736,-0.036222,-0.023377,-0.039330,-0.110074,0.005193,-0.003728
Premis Cd,-0.008836,-0.089303,0.006558,0.006488,0.232997,0.104818,0.167660,1.000000,0.211237,0.104862,-0.049968,-0.020172,0.152314,0.003682,-0.001689
Weapon Used Cd,0.003959,-0.003194,-0.008430,-0.008246,0.433431,0.419119,0.080736,0.211237,1.000000,0.419638,-0.138583,-0.029485,-0.067588,0.004880,-0.000652
Crm Cd 1,-0.005867,0.011771,-0.004800,-0.004864,0.730883,0.999502,-0.036222,0.104862,0.419638,1.000000,0.052682,0.141932,0.084568,-0.004193,0.005507
Crm Cd 2,-0.103905,0.013172,-0.056716,-0.056097,0.075398,0.038707,-0.023377,-0.049968,-0.138583,0.052682,1.000000,0.294290,0.289299,-0.002787,0.006743
Crm Cd 3,0.026345,0.003855,-0.019490,-0.018183,-0.044188,0.109604,-0.039330,-0.020172,-0.029485,0.141932,0.294290,1.000000,0.447195,0.000763,0.004004
Crm Cd 4,0.143807,-0.081183,0.062950,0.063716,0.105500,0.097887,-0.110074,0.152314,-0.067588,0.084568,0.289299,0.447195,1.000000,-0.003420,0.063741
LAT,0.002444,0.000933,0.046315,0.045968,-0.001571,-0.004234,0.005193,0.003682,0.004880,-0.004193,-0.002787,0.000763,-0.003420,1.000000,-0.992053
LON,-0.000516,-0.000251,-0.010540,-0.010623,0.003934,0.005549,-0.003728,-0.001689,-0.000652,0.005507,0.006743,0.004004,0.063741,-0.992053,1.000000